sudo: required
language: node_js
node_js:
- '9'
services:
- docker
before_install:
- "./scripts/build_test_images.sh"
script:
- "./scripts/run_tests.sh"
after_success:
- "./scripts/push_to_docker.sh"
deploy:
  on:
    branch: master
  provider: script
  script: bash ./scripts/push_to_heroku.sh
  api_key:
    secure: IJ2mPujFoqFgoMRW8D0auqYp6KqcL5U7cRTHd+6Qi+M5nNIZaeDDSGZp/bPM8j0bnFDtdQ0VTxgt/VH6kdyKZJzlv/FD1vRIE49vEqBimNQq1OzDDX96SjEXuOqZNZSmHybNARiUUnyraJbJx8k+idWY06u9mlScfiYg3d9th4lj7ALGZW8OpNkkGzyK0JbjT0/jlr+bKhlar7t/ImGStOKTCcS2sUn7+8fqlvPh4ZOjVpk3+emcWTY+roq/UiJX0QhJ0rD4Z2EC7MF1cVMmddxv1QUCLhRmtLrAOVFDK+IRqkBEmmztStrMMpDH1uJYSi6fSJaMOiZArI3A8bIy8NLLM+tCx71jLMk5b921g1FTABU3Befb32SEtRTuxjBHUy6UYHbJhabsIMXdlW6FNLX3NJUmMxcLZSdLNOrsYMtHVkiYByChizAezoVSug7P5Yl7jI+dSTU+VRQrK9h8dy3jPtiDXjPfJZ/t0RyRJ1zMG/XlNTCqtgnvCluCHzy8VXuGuTD7i2aRR8AomOl9wjHd+JAyGbS9ARWAbr+TN4wzqPY7yVz7vD+m1Y2jwvNiO6xdguclfJp5vHhrKT3Y67LXR33aW/jOt7agxP3E5uhiA6ZvuMac+shjXQsaIP0D0a86Zj8dHPtAgh+M9PsqDsKVRWfUq2padqNDtdwpXNo=
after_deploy:
- "./scripts/release_heroku_containers.sh"
