version: '3'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
  api:
    depends_on: [prisma]
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - api_node_modules:/app/node_modules
      - ./api:/app
  prisma:
    depends_on: [mysql]
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
      - 4466:4466
    environment:
      # PRISMA_SECRET: randomprismasecret1234
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma_pass
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma_pass
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  client_node_modules:
  api_node_modules:
  mysql:
